### ISSUE TITLE
compass calibration stock drone 

### ISSUE THREAD

**Issue by JSostorecz** [OpenSolo/documentation#12]
yes i have a stock 3dr that i just bought first i was fighting the preflight update so i installed opensolo4 and now i cannot seem to get my drone to calibrate the compass. it errors every time i get to the end of the calibration the drone makes all the beeps but as soon as its done it errors.

**Comment by davidbuzz** [comment]
please see the Arduplot documentation on how to perform a compass calibration, this is not an issue in Opensolo. https://ardupilot.org/copter/docs/common-compass-calibration-in-mission-planner.html
