### ISSUE TITLE
Add more architectural documentation?

### ISSUE THREAD

**Issue by k4kfh** [OpenSolo/documentation#6]
I think you guys have done an excellent job with this software, and the instructions right now are fairly easy to follow if you're the developer type and already know quite a bit about Solo. However for a new user just getting into Solo (or just getting into Open Solo, anyway) I think it would be helpful to have some explanation about what exactly Open Solo is going to change when they install it. Something similar to the "architectural overview" diagram on the old 3DR dev guide, except maybe a little higher level. Just to introduce the users to the concepts of all the different individual devices involved in this, and make sure they understand what they're getting into.

I've got a copy of MS Visio I could use to make some nice looking diagrams, and I understand the general idea of how the Solo's parts fit together, but some more information on the network communication would be very helpful. What ports does the controller use to talk to the Solo? What ports does the app use? If someone can explain that a little for me I will try and put together a couple diagrams this week.

Thanks again for your hard work on this! This is a big step for Solo owners.

**Comment by davidbuzz** [comment]
If you draw-up some diagrams that will be helpful to the community, we're happy to accept them as  PR to the repo.
